from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import svgwrite

from .config import PipelineConfig
from .tracing import TraceResult


def build_svg(trace: TraceResult, size: tuple[int, int], config: PipelineConfig, source: Path) -> str:
    width, height = size
    dwg = svgwrite.Drawing(size=(width, height), profile="full")
    dwg.viewbox(0, 0, width, height)

    if config.embed_metadata:
        meta = (
            f"Generated by Imagetosvg pipeline | detail={config.detail.value} | "
            f"source={source.name} | timestamp={datetime.now(UTC).isoformat()}"
        )
        dwg.add(dwg.metadata(meta))

    for layer in trace.layers:
        group = dwg.g(id=layer.name, opacity=layer.opacity)
        for d in layer.paths:
            path_kwargs = {
                "d": d,
                "fill": layer.fill or "none",
                "fill_rule": "evenodd",
                "shape_rendering": "geometricPrecision",
            }
            if layer.stroke:
                path_kwargs["stroke"] = layer.stroke
                path_kwargs["stroke_width"] = layer.stroke_width or 0.35
                path_kwargs["stroke_linejoin"] = "round"
                path_kwargs["stroke_linecap"] = "round"
            group.add(dwg.path(**path_kwargs))
        dwg.add(group)

    return dwg.tostring()
